version: "3.8"

services:
  mysql-super:
    image: mysql-super-rolling
    environment:
      #- SUPER_PASSWORD=my_password
      SUPER_PASSWORD_FILE: "/run/secrets/db_superadmin_paswd" # use docker secret to protect sensitive information
      SUPER_USER_FILE: "/run/secrets/db_superadmin" # use docker secret to protect sensitive information
      DB_HOST: "mariadb_maxscale"
      DB_PORT: "6033"
      DB_USER: "super_usr"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    secrets:
      - db_superadmin
      - db_superadmin_paswd
    networks:
      - mariadb-network

secrets:
  db_superadmin:
    external: true
  db_superadmin_paswd:
    external: true

networks:
  mariadb-network:
    external: true
