version: "3.8"

services:
  username1: # << Change | service name for each users : username1, username2
    image: mysql-user-rolling
    secrets:
      - db_host
      - db_port
      - db_super_user
      - db_super_paswd
    environment:
      DB_PREFIX: "dbname" # << Change | give all access to db with prefix dbname_
      DB_USER: "project_usr" # << Change
      PMA_USER: "pma_user"
      PMA_PASS: "insert_from_pma_htpasswd" # << Change
      PMA_URL: "http://pma.secure.domain.com" # << Change
      DB_REMOTE_HOST: "db.secure.domain.com" # << Change
      GITLAB_API_URL: "https://repo.cic-webpro.com" # << Change
      GITLAB_TOKEN: "your_personal_access_token" # << Change
      GITLAB_PROJECT_ID: "your_project_id" # << Change
      GITLAB_SNIPPET_TITLE: "Database Credential"
      SUPER_PASSWORD_FILE: "/run/secrets/db_super_paswd" # use docker secret to protect sensitive information
      SUPER_USER_FILE: "/run/secrets/db_super_user" # use docker secret to protect sensitive information
      DB_HOST_FILE: "/run/secrets/db_host" # use docker secret to protect sensitive information
      DB_PORT_FILE: "/run/secrets/db_port" # use docker secret to protect sensitive information
      SQL_SERVICE: "mariadb" # Set mariadb/mysql service
      ENABLE_SSL: "false" # << Set to true or false
    #volumes:
      #- /etc/secure/mariadb/tls:/etc/my.cnf.d/tls # Uncomment if ENABLE_SSL: true >> Change with your ssl/tls location path
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - mariadb-network

  ## ------------------------------
  ## ADD addtional user below
  ## ------------------------------
  # username2: # << Change | service name for each users : mysql-user1, mysql-user2
  #   image: mysql-user-rolling
  #   secrets:
  #     - db_host
  #     - db_port
  #     - db_superadmin
  #     - db_superadmin_paswd
  #   environment:
  #     DB_PREFIX: "dbname" # << Change | give all access to db with prefix dbname_
  #     DB_USER: "project_usr" # << Change
  #     PMA_USER: "pma_user"
  #     PMA_PASS: "insert_from_pma_htpasswd" # << Change
  #     PMA_URL: "http://pma.secure.domain.com" # << Change
  #     DB_REMOTE_HOST: "db.secure.domain.com" # << Change
  #     GITLAB_API_URL: "https://repo.cic-webpro.com" # << Change
  #     GITLAB_TOKEN: "your_personal_access_token" # << Change
  #     GITLAB_PROJECT_ID: "your_project_id" # << Change
  #     GITLAB_SNIPPET_TITLE: "Database Credential"
  #     SUPER_PASSWORD_FILE: "/run/secrets/db_superadmin_paswd" # use docker secret to protect sensitive information
  #     SUPER_USER_FILE: "/run/secrets/db_superadmin" # use docker secret to protect sensitive information
  #     DB_HOST_FILE: "/run/secrets/db_host" # use docker secret to protect sensitive information
  #     DB_PORT_FILE: "/run/secrets/db_port" # use docker secret to protect sensitive information
  #     SQL_SERVICE: "mariadb" # Set mariadb/mysql service
  #     ENABLE_SSL: "false" # << Set to true or false
  #   #volumes:
  #     #- /etc/secure/mariadb/tls:/etc/my.cnf.d/tls # Uncomment if ENABLE_SSL: true >> Change with your ssl/tls location path
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       order: start-first
  #       delay: 1s
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       window: 120s
  #       max_attempts: 2
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: "512M"
  #   networks:
  #     - mariadb-network

secrets:
  db_host:
    external: true
  db_port:
    external: true
  db_super_user:
    external: true
  db_super_paswd:
    external: true
    
networks:
  mariadb-network:
    external: true
